on: [push]

jobs:
  updater:
    runs-on: ubuntu-latest
    name: Sample usage
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: MaxMind GeoIP Updater
        uses: yortyrh/geoipupdate-action@v4
        id: updater
        with:
          account-id: ${{ secrets.GEOIPUPDATE_ACCOUNT_ID }}
          license-key: ${{ secrets.GEOIPUPDATE_LICENSE_KEY }}
          edition-ids: 'GeoLite2-City'
          db-path: 'dbs'

      - name: List files
        run: |
          ls -l dbs
